# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(676, 371)
        self.quitButton = QtWidgets.QPushButton(Form)
        self.quitButton.setGeometry(QtCore.QRect(600, 0, 75, 23))
        self.quitButton.setObjectName("quitButton")
        self.formatComboBox = QtWidgets.QComboBox(Form)
        self.formatComboBox.setGeometry(QtCore.QRect(120, 70, 131, 31))
        self.formatComboBox.setObjectName("formatComboBox")
        self.formatLabel = QtWidgets.QLabel(Form)
        self.formatLabel.setGeometry(QtCore.QRect(40, 80, 61, 16))
        self.formatLabel.setObjectName("formatLabel")
        self.titleLabel = QtWidgets.QLabel(Form)
        self.titleLabel.setGeometry(QtCore.QRect(70, 20, 181, 41))
        self.titleLabel.setObjectName("titleLabel")
        self.consoleTextEdit = QtWidgets.QTextEdit(Form)
        self.consoleTextEdit.setGeometry(QtCore.QRect(0, 200, 381, 171))
        self.consoleTextEdit.setObjectName("consoleTextEdit")
        self.outputPathLabel = QtWidgets.QLabel(Form)
        self.outputPathLabel.setGeometry(QtCore.QRect(40, 120, 47, 13))
        self.outputPathLabel.setObjectName("outputPathLabel")
        self.outputPathDisplayLabel = QtWidgets.QLabel(Form)
        self.outputPathDisplayLabel.setGeometry(QtCore.QRect(120, 120, 131, 16))
        self.outputPathDisplayLabel.setObjectName("outputPathDisplayLabel")
        self.selectOutputPathButton = QtWidgets.QPushButton(Form)
        self.selectOutputPathButton.setGeometry(QtCore.QRect(290, 110, 111, 23))
        self.selectOutputPathButton.setObjectName("selectOutputPathButton")
        self.linkLabel = QtWidgets.QLabel(Form)
        self.linkLabel.setGeometry(QtCore.QRect(40, 160, 47, 13))
        self.linkLabel.setObjectName("linkLabel")
        self.linkLineEdit = QtWidgets.QLineEdit(Form)
        self.linkLineEdit.setGeometry(QtCore.QRect(120, 160, 151, 20))
        self.linkLineEdit.setObjectName("linkLineEdit")
        self.downloadButton = QtWidgets.QPushButton(Form)
        self.downloadButton.setGeometry(QtCore.QRect(460, 200, 111, 61))
        self.downloadButton.setObjectName("downloadButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.quitButton.setText(_translate("Form", "PushButton"))
        self.formatLabel.setText(_translate("Form", "TextLabel"))
        self.titleLabel.setText(_translate("Form", "TextLabel"))
        self.outputPathLabel.setText(_translate("Form", "TextLabel"))
        self.outputPathDisplayLabel.setText(_translate("Form", "TextLabel"))
        self.selectOutputPathButton.setText(_translate("Form", "PushButton"))
        self.linkLabel.setText(_translate("Form", "TextLabel"))
        self.downloadButton.setText(_translate("Form", "PushButton"))
